version: "3.8"

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://wiki.infernalaquatics.com
      - DB_CONNECTION=mysql
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_DATABASE=bookstackapp
      - DB_USER=bookstack
      - DB_PASS=e9a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1
      - APP_DEFAULT_DARK_MODE=true
      - APP_KEY=Pii9bTvR3SK2/5es+fA+F8+DSF4KZidbJN95nYdrXaM=
    ports:
      - "8091:80"
    volumes:
      - ./bookstack_config:/config
    networks:
      - bookstack-network
    depends_on:
      - bookstack_db
    restart: unless-stopped
    #command: /init && apt-get update && apt-get install -y php82-pgsql && rm -rf /var/lib/apt/lists/*
networks:
  bookstack-network:
    external: true
